name: sharegpt-analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip>=21.0
  - numpy>=1.21.0
  - pandas>=1.3.0
  - nltk>=3.6.0
  - jupyter>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - pip:
    - vaderSentiment>=3.3.2
    - langdetect>=1.0.9
    - openai>=1.0.0
    - tqdm>=4.65.0
    - aiohttp>=3.8.0
    - plotly>=5.3.0
    - python-dotenv>=0.19.0